import type { Question } from "./types"

export const questionsData: Question[] = [
  {
    id: "q1",
    text: "O que significa um sinal triangular vermelho com uma bicicleta?",
    options: {
      A: "Proibido andar de bicicleta",
      B: "Atenção: ciclistas na via",
      C: "Pista exclusiva para bicicletas",
      D: "Estacionamento para bicicletas",
    },
    correctAnswer: "B",
    category: "traffic-signs",
    explanation:
      "Sinais triangulares vermelhos são sinais de advertência que alertam para perigos à frente. Neste caso, indica a presença de ciclistas na via.",
  },
  {
    id: "q2",
    text: "Um sinal circular azul com uma seta branca indica:",
    options: {
      A: "Direção proibida",
      B: "Direção obrigatória",
      C: "Direção recomendada",
      D: "Desvio temporário",
    },
    correctAnswer: "B",
    category: "traffic-signs",
    explanation:
      "Sinais circulares azuis são sinais de obrigação. Uma seta branca indica a direção obrigatória que deve seguir.",
  },
  {
    id: "q3",
    text: "O que significa um sinal circular vermelho com uma barra branca horizontal?",
    options: {
      A: "Estacionamento proibido",
      B: "Entrada proibida",
      C: "Sentido proibido",
      D: "Paragem obrigatória",
    },
    correctAnswer: "C",
    category: "traffic-signs",
    explanation: "Este sinal indica sentido proibido. Nenhum veículo pode entrar na via nesta direção.",
  },
  {
    id: "q4",
    text: "Numa rotunda, quem tem prioridade?",
    options: {
      A: "Quem entra na rotunda",
      B: "Quem já está a circular na rotunda",
      C: "O veículo maior",
      D: "O veículo da direita",
    },
    correctAnswer: "B",
    category: "priority-rules",
    explanation:
      "Nas rotundas, os veículos que já estão a circular têm sempre prioridade sobre os que pretendem entrar.",
  },
  {
    id: "q5",
    text: "Num cruzamento sem sinalização, quem tem prioridade?",
    options: {
      A: "O veículo da esquerda",
      B: "O veículo da direita",
      C: "O veículo mais rápido",
      D: "O veículo maior",
    },
    correctAnswer: "B",
    category: "priority-rules",
    explanation:
      "Na ausência de sinalização, aplica-se a regra da prioridade à direita. O veículo que vem da direita tem prioridade.",
  },
  {
    id: "q6",
    text: "Ao aproximar-se de uma passadeira, o condutor deve:",
    options: {
      A: "Acelerar para passar rapidamente",
      B: "Buzinar para avisar os peões",
      C: "Reduzir a velocidade e ceder passagem aos peões",
      D: "Manter a velocidade se não houver peões",
    },
    correctAnswer: "C",
    category: "priority-rules",
    explanation:
      "Os peões têm sempre prioridade nas passadeiras. O condutor deve reduzir a velocidade e estar preparado para parar.",
  },
  {
    id: "q7",
    text: "Qual é o limite de velocidade dentro das localidades?",
    options: {
      A: "40 km/h",
      B: "50 km/h",
      C: "60 km/h",
      D: "70 km/h",
    },
    correctAnswer: "C",
    category: "speed-limits",
    explanation:
      "O limite de velocidade dentro das localidades em Moçambique é de 60 km/h, salvo indicação em contrário.",
  },
  {
    id: "q8",
    text: "Nas auto-estradas, o limite de velocidade é:",
    options: {
      A: "100 km/h",
      B: "120 km/h",
      C: "140 km/h",
      D: "160 km/h",
    },
    correctAnswer: "B",
    category: "speed-limits",
    explanation: "O limite máximo de velocidade nas auto-estradas é de 120 km/h para veículos ligeiros.",
  },
  {
    id: "q9",
    text: "Em condições de chuva, o condutor deve:",
    options: {
      A: "Manter a mesma velocidade",
      B: "Aumentar a velocidade",
      C: "Reduzir a velocidade",
      D: "Parar imediatamente",
    },
    correctAnswer: "C",
    category: "speed-limits",
    explanation:
      "Em condições de chuva, a aderência diminui e a visibilidade é reduzida. Deve sempre reduzir a velocidade.",
  },
  {
    id: "q10",
    text: "Conduzir sob efeito de álcool é:",
    options: {
      A: "Permitido se for pouco",
      B: "Uma infração grave",
      C: "Permitido fora das cidades",
      D: "Uma infração leve",
    },
    correctAnswer: "B",
    category: "infractions",
    explanation:
      "Conduzir sob efeito de álcool é uma infração muito grave que pode resultar em suspensão da carta e multa pesada.",
  },
  {
    id: "q11",
    text: "Usar o telemóvel enquanto conduz sem dispositivo mãos-livres:",
    options: {
      A: "É permitido em emergências",
      B: "É uma infração",
      C: "É permitido a baixa velocidade",
      D: "É permitido fora das cidades",
    },
    correctAnswer: "B",
    category: "infractions",
    explanation:
      "Usar o telemóvel sem dispositivo mãos-livres é uma infração. Distrai o condutor e aumenta o risco de acidentes.",
  },
  {
    id: "q12",
    text: "Não usar cinto de segurança é:",
    options: {
      A: "Opcional para adultos",
      B: "Obrigatório apenas na auto-estrada",
      C: "Uma infração punível com multa",
      D: "Opcional em trajetos curtos",
    },
    correctAnswer: "C",
    category: "infractions",
    explanation:
      "O uso do cinto de segurança é obrigatório para todos os ocupantes do veículo. Não usar é uma infração.",
  },
  {
    id: "q13",
    text: "Antes de ultrapassar, o condutor deve:",
    options: {
      A: "Buzinar e ultrapassar rapidamente",
      B: "Verificar se tem visibilidade e espaço suficiente",
      C: "Ligar as luzes de emergência",
      D: "Acelerar ao máximo",
    },
    correctAnswer: "B",
    category: "general-rules",
    explanation:
      "Antes de ultrapassar, deve certificar-se de que tem visibilidade, espaço suficiente e que não coloca em risco outros utentes.",
  },
  {
    id: "q14",
    text: "Ao estacionar numa subida, deve:",
    options: {
      A: "Deixar o veículo em ponto morto",
      B: "Virar as rodas para a berma",
      C: "Virar as rodas para a estrada",
      D: "Não usar o travão de mão",
    },
    correctAnswer: "C",
    category: "general-rules",
    explanation: "Numa subida, deve virar as rodas para a estrada para que, se o veículo se mover, não vá para a via.",
  },
  {
    id: "q15",
    text: "Os retrovisores devem ser ajustados:",
    options: {
      A: "Apenas uma vez por mês",
      B: "Antes de iniciar a marcha",
      C: "Durante a condução",
      D: "Apenas quando mudar de condutor",
    },
    correctAnswer: "B",
    category: "general-rules",
    explanation: "Os retrovisores devem ser ajustados antes de iniciar a marcha para garantir boa visibilidade.",
  },
  {
    id: "q16",
    text: "Em caso de acidente, a primeira coisa a fazer é:",
    options: {
      A: "Sair do local rapidamente",
      B: "Tirar fotografias",
      C: "Garantir a segurança e chamar socorro",
      D: "Discutir com o outro condutor",
    },
    correctAnswer: "C",
    category: "safety",
    explanation:
      "A prioridade é sempre garantir a segurança de todos e chamar os serviços de emergência se necessário.",
  },
  {
    id: "q17",
    text: "O triângulo de sinalização deve ser colocado a que distância do veículo?",
    options: {
      A: "10 metros",
      B: "30 metros",
      C: "50 metros",
      D: "100 metros",
    },
    correctAnswer: "B",
    category: "safety",
    explanation:
      "O triângulo deve ser colocado a pelo menos 30 metros do veículo para alertar outros condutores com antecedência.",
  },
  {
    id: "q18",
    text: "Ao conduzir com nevoeiro, deve:",
    options: {
      A: "Usar luzes de máximos",
      B: "Usar luzes de nevoeiro e reduzir velocidade",
      C: "Seguir muito próximo do veículo da frente",
      D: "Desligar todas as luzes",
    },
    correctAnswer: "B",
    category: "safety",
    explanation: "Com nevoeiro, use luzes de nevoeiro, reduza a velocidade e aumente a distância de segurança.",
  },
  {
    id: "q19",
    text: "A distância de segurança entre veículos deve ser:",
    options: {
      A: "Pelo menos 2 segundos",
      B: "Pelo menos 5 metros",
      C: "Não é necessária em cidade",
      D: "Apenas em auto-estrada",
    },
    correctAnswer: "A",
    category: "safety",
    explanation: "Deve manter uma distância de pelo menos 2 segundos do veículo da frente para ter tempo de reagir.",
  },
  {
    id: "q20",
    text: "Ao aproximar-se de um veículo de emergência com sinais ligados, deve:",
    options: {
      A: "Manter a velocidade",
      B: "Acelerar para passar",
      C: "Reduzir velocidade e facilitar a passagem",
      D: "Parar imediatamente",
    },
    correctAnswer: "C",
    category: "priority-rules",
    explanation: "Deve reduzir a velocidade e, se possível, facilitar a passagem dos veículos de emergência.",
  },
  {
    id: "q21",
    text: "É obrigatório ter no veículo:",
    options: {
      A: "Apenas o documento do veículo",
      B: "Triângulo, colete refletor e extintor",
      C: "Apenas a carta de condução",
      D: "Apenas o seguro",
    },
    correctAnswer: "B",
    category: "general-rules",
    explanation: "É obrigatório ter triângulo de sinalização, colete refletor e extintor no veículo.",
  },
  {
    id: "q22",
    text: "Ao mudar de faixa, deve:",
    options: {
      A: "Fazer rapidamente sem sinalizar",
      B: "Sinalizar, verificar espelhos e ponto cego",
      C: "Apenas sinalizar",
      D: "Buzinar antes de mudar",
    },
    correctAnswer: "B",
    category: "general-rules",
    explanation: "Deve sempre sinalizar, verificar os espelhos e o ponto cego antes de mudar de faixa.",
  },
  {
    id: "q23",
    text: "A luz amarela do semáforo significa:",
    options: {
      A: "Acelerar para passar",
      B: "Parar se for seguro fazê-lo",
      C: "Continuar sempre",
      D: "Buzinar e passar",
    },
    correctAnswer: "B",
    category: "traffic-signs",
    explanation: "A luz amarela indica que deve parar se puder fazê-lo em segurança. Não é sinal para acelerar.",
  },
  {
    id: "q24",
    text: "Crianças com menos de 12 anos devem:",
    options: {
      A: "Viajar no banco da frente",
      B: "Viajar no banco de trás com sistema de retenção adequado",
      C: "Viajar sem cinto se for trajeto curto",
      D: "Viajar ao colo de um adulto",
    },
    correctAnswer: "B",
    category: "safety",
    explanation:
      "Crianças menores de 12 anos devem viajar no banco de trás com sistema de retenção adequado à sua idade e tamanho.",
  },
  {
    id: "q25",
    text: "Ao aproximar-se de um autocarro parado, deve:",
    options: {
      A: "Ultrapassar rapidamente",
      B: "Reduzir velocidade e ter atenção aos peões",
      C: "Buzinar para avisar",
      D: "Manter a velocidade",
    },
    correctAnswer: "B",
    category: "safety",
    explanation: "Deve reduzir a velocidade pois podem surgir peões a atravessar, especialmente crianças.",
  },
  {
    id: "q26",
    text: "A carta de condução deve ser renovada:",
    options: {
      A: "Nunca",
      B: "De 5 em 5 anos",
      C: "De 10 em 10 anos",
      D: "Apenas quando solicitado",
    },
    correctAnswer: "C",
    category: "general-rules",
    explanation: "A carta de condução deve ser renovada periodicamente, geralmente de 10 em 10 anos.",
  },
  {
    id: "q27",
    text: "Estacionar em cima de uma passadeira é:",
    options: {
      A: "Permitido se for rápido",
      B: "Uma infração grave",
      C: "Permitido à noite",
      D: "Permitido se não houver peões",
    },
    correctAnswer: "B",
    category: "infractions",
    explanation: "Estacionar em passadeiras é uma infração grave pois coloca os peões em perigo.",
  },
  {
    id: "q28",
    text: "Ao conduzir à noite, deve:",
    options: {
      A: "Usar sempre luzes de máximos",
      B: "Usar médios e mudar para máximos quando apropriado",
      C: "Usar apenas luzes de presença",
      D: "Não usar luzes em zonas iluminadas",
    },
    correctAnswer: "B",
    category: "general-rules",
    explanation: "Deve usar luzes de médios e mudar para máximos quando não houver tráfego em sentido contrário.",
  },
  {
    id: "q29",
    text: "Se os travões falharem, deve:",
    options: {
      A: "Saltar do veículo",
      B: "Usar o travão de mão gradualmente e reduzir mudanças",
      C: "Acelerar para parar mais rápido",
      D: "Desligar o motor imediatamente",
    },
    correctAnswer: "B",
    category: "safety",
    explanation:
      "Deve usar o travão de mão gradualmente e reduzir as mudanças para diminuir a velocidade com segurança.",
  },
  {
    id: "q30",
    text: "A pressão dos pneus deve ser verificada:",
    options: {
      A: "Apenas quando parecem vazios",
      B: "Regularmente, pelo menos uma vez por mês",
      C: "Apenas antes de viagens longas",
      D: "Nunca é necessário",
    },
    correctAnswer: "B",
    category: "safety",
    explanation:
      "A pressão dos pneus deve ser verificada regularmente para garantir segurança e eficiência do veículo.",
  },
]
